services:
  api_service:
    image: nadezhda630/server
    restart: always
    ports:
      - 8083:8083
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/foodsaver?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
      - spring.datasource.password=
      - server.port=8083
      - secret.key=yvKlZIBeMDUA3s6saNgBpWHX65tJ+0WVs6Nqv9qhycYMVb4vZ0LqDtp6uMiI5gFv
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/foodsaver?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
      - spring.datasource.password=
      - server.port=8083
      - secret.key=yvKlZIBeMDUA3s6saNgBpWH
      - X65tJ+0WVs6Nqv9qhycYMVb4vZ0LqDtp6uMiI5gFv

  client_service:
    build: ../../client
    image: nadezhda630/client
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    depends_on:
      - api_service

networks:
  springapimysql-net:
