CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE CHECK(CHAR_LENGTH(username) <= 25),
    password VARCHAR(255) NOT NULL CHECK(CHAR_LENGTH(password) >= 8),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1
);